# Generated by Django 3.2.6 on 2021-08-27 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_rename_user_subtype_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknews',
            name='users',
        ),
        migrations.AddField(
            model_name='stocknews',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
