# Generated by Django 3.2.6 on 2021-08-27 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0004_alter_stocknews_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
