# Generated by Django 3.2.6 on 2021-08-27 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0006_alter_stocknews_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknews',
            name='users',
        ),
        migrations.AddField(
            model_name='stocknews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
