# Generated by Django 3.2.6 on 2021-08-27 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0007_auto_20210827_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknews',
            name='user',
        ),
        migrations.AddField(
            model_name='stocknews',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
