# Generated by Django 3.2.6 on 2021-08-27 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0008_auto_20210827_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknews',
            name='users',
        ),
        migrations.AddField(
            model_name='subtype',
            name='stock_subed',
            field=models.ManyToManyField(blank=True, to='stocks.Stocknews'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
