# Generated by Django 3.2.6 on 2021-08-27 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0009_auto_20210827_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtype',
            name='stock_subed',
        ),
        migrations.AddField(
            model_name='stocknews',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
