# Generated by Django 3.2.6 on 2021-08-27 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0010_auto_20210827_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
