# Generated by Django 3.2.6 on 2021-08-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_subtype_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocknews',
            name='users',
        ),
        migrations.AddField(
            model_name='subtype',
            name='stock_ticker',
            field=models.ManyToManyField(blank=True, to='stocks.Stocknews'),
        ),
    ]
