# Generated by Django 3.2.6 on 2021-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20210828_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtype',
            old_name='users',
            new_name='user',
        ),
    ]
