# Generated by Django 3.2.6 on 2021-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_subtype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='daily_sub',
            field=models.BooleanField(default=True),
        ),
    ]
